/*-
 * ========================LICENSE_START=================================
 * TeamApps Icons8 Flat Color Icon Provider
 * ---
 * Copyright (C) 2014 - 2019 TeamApps.org
 * ---
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =========================LICENSE_END==================================
 */
package org.teamapps.icon.icon8;

import org.teamapps.icons.api.SimpleIcon;

public enum FlagIcon implements SimpleIcon {

	AD_ANDORRA("ad.svg"),
	AE_UNITED_ARAB_EMIRATES("ae.svg"),
	AF_AFGHANISTAN("af.svg"),
	AG_ANTIGUA_BARBUDA("ag.svg"),
	AI_ANGUILLA("ai.svg"),
	AL_ALBANIA("al.svg"),
	AM_ARMENIA("am.svg"),
	AO_ANGOLA("ao.svg"),
	AQ_ANTARCTICA("aq.svg"),
	AR_ARGENTINA("ar.svg"),
	AS_AMERICAN_SAMOA("as.svg"),
	AT_AUSTRIA("at.svg"),
	AU_AUSTRALIA("au.svg"),
	AW_ARUBA("aw.svg"),
	AX_ALAND_ISLANDS("ax.svg"),
	AZ_AZERBAIJAN("az.svg"),
	BA_BOSNIA("ba.svg"),
	BB_BARBADOS("bb.svg"),
	BD_BANGLADESH("bd.svg"),
	BE_BELGIUM("be.svg"),
	BF_BURKINA_FASO("bf.svg"),
	BG_BULGARIA("bg.svg"),
	BH_BAHRAIN("bh.svg"),
	BI_BURUNDI("bi.svg"),
	BJ_BENIN("bj.svg"),
	BL_ST_BARTHELEMY("bl.svg"),
	BM_BERMUDA("bm.svg"),
	BN_BRUNEI("bn.svg"),
	BO_BOLIVIA("bo.svg"),
	BQ_CARIBBEAN_NETHERLANDS("bq.svg"),
	BR_BRAZIL("br.svg"),
	BS_BAHAMAS("bs.svg"),
	BT_BHUTAN("bt.svg"),
	BV_BOUVET_ISLAND("bv.svg"),
	BW_BOTSWANA("bw.svg"),
	BY_BELARUS("by.svg"),
	BZ_BELIZE("bz.svg"),
	CA_CANADA("ca.svg"),
	CC_COCOS_ISLANDS("cc.svg"),
	CD_CONGO__KINSHASA("cd.svg"),
	CF_CENTRAL_AFRICAN_REPUBLIC("cf.svg"),
	CG_CONGO__BRAZZAVILLE("cg.svg"),
	CH_SWITZERLAND("ch.svg"),
	CI_COTE_D_IVOIRE("ci.svg"),
	CK_COOK_ISLANDS("ck.svg"),
	CL_CHILE("cl.svg"),
	CM_CAMEROON("cm.svg"),
	CN_CHINA("cn.svg"),
	CO_COLOMBIA("co.svg"),
	CR_COSTA_RICA("cr.svg"),
	CU_CUBA("cu.svg"),
	CV_CAPE_VERDE("cv.svg"),
	CW_CURACAO("cw.svg"),
	CX_CHRISTMAS_ISLAND("cx.svg"),
	CY_CYPRUS("cy.svg"),
	CZ_CZECHIA("cz.svg"),
	DE_GERMANY("de.svg"),
	DJ_DJIBOUTI("dj.svg"),
	DK_DENMARK("dk.svg"),
	DM_DOMINICA("dm.svg"),
	DO_DOMINICAN_REPUBLIC("do.svg"),
	DZ_ALGERIA("dz.svg"),
	EC_ECUADOR("ec.svg"),
	EE_ESTONIA("ee.svg"),
	EG_EGYPT("eg.svg"),
	EH_WESTERN_SAHARA("eh.svg"),
	ER_ERITREA("er.svg"),
	ES_CT("es-ct.svg"),
	ES_SPAIN("es.svg"),
	ET_ETHIOPIA("et.svg"),
	EU_EUROPEAN_UNION("eu.svg"),
	FI_FINLAND("fi.svg"),
	FJ_FIJI("fj.svg"),
	FK_FALKLAND_ISLANDS("fk.svg"),
	FM_MICRONESIA("fm.svg"),
	FO_FAROE_ISLANDS("fo.svg"),
	FR_FRANCE("fr.svg"),
	GA_GABON("ga.svg"),
	GB_ENG("gb-eng.svg"),
	GB_NIR("gb-nir.svg"),
	GB_SCT("gb-sct.svg"),
	GB_WLS("gb-wls.svg"),
	GB_GREAT_BRITAIN("gb.svg"),
	GD_GRENADA("gd.svg"),
	GE_GEORGIA("ge.svg"),
	GF_FRENCH_GUIANA("gf.svg"),
	GG_GUERNSEY("gg.svg"),
	GH_GHANA("gh.svg"),
	GI_GIBRALTAR("gi.svg"),
	GL_GREENLAND("gl.svg"),
	GM_GAMBIA("gm.svg"),
	GN_GUINEA("gn.svg"),
	GP_GUADELOUPE("gp.svg"),
	GQ_EQUATORIAL_GUINEA("gq.svg"),
	GR_GREECE("gr.svg"),
	GS_SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS("gs.svg"),
	GT_GUATEMALA("gt.svg"),
	GU_GUAM("gu.svg"),
	GW_GUINEA_BISSAU("gw.svg"),
	GY_GUYANA("gy.svg"),
	HK_HONG_KONG("hk.svg"),
	HM_HEARD_MCDONALD_ISLANDS("hm.svg"),
	HN_HONDURAS("hn.svg"),
	HR_CROATIA("hr.svg"),
	HT_HAITI("ht.svg"),
	HU_HUNGARY("hu.svg"),
	ID_INDONESIA("id.svg"),
	IE_IRELAND("ie.svg"),
	IL_ISRAEL("il.svg"),
	IM_ISLE_OF_MAN("im.svg"),
	IN_INDIA("in.svg"),
	IO_BRITISH_INDIAN_OCEAN_TERRITORY("io.svg"),
	IQ_IRAQ("iq.svg"),
	IR_IRAN("ir.svg"),
	IS_ICELAND("is.svg"),
	IT_ITALY("it.svg"),
	JE_JERSEY("je.svg"),
	JM_JAMAICA("jm.svg"),
	JO_JORDAN("jo.svg"),
	JP_JAPAN("jp.svg"),
	KE_KENYA("ke.svg"),
	KG_KYRGYZSTAN("kg.svg"),
	KH_CAMBODIA("kh.svg"),
	KI_KIRIBATI("ki.svg"),
	KM_COMOROS("km.svg"),
	KN_ST_KITTS_NEVIS("kn.svg"),
	KP_NORTH_KOREA("kp.svg"),
	KR_SOUTH_KOREA("kr.svg"),
	KW_KUWAIT("kw.svg"),
	KY_CAYMAN_ISLANDS("ky.svg"),
	KZ_KAZAKHSTAN("kz.svg"),
	LA_LAOS("la.svg"),
	LB_LEBANON("lb.svg"),
	LC_ST_LUCIA("lc.svg"),
	LI_LIECHTENSTEIN("li.svg"),
	LK_SRI_LANKA("lk.svg"),
	LR_LIBERIA("lr.svg"),
	LS_LESOTHO("ls.svg"),
	LT_LITHUANIA("lt.svg"),
	LU_LUXEMBOURG("lu.svg"),
	LV_LATVIA("lv.svg"),
	LY_LIBYA("ly.svg"),
	MA_MOROCCO("ma.svg"),
	MC_MONACO("mc.svg"),
	MD_MOLDOVA("md.svg"),
	ME_MONTENEGRO("me.svg"),
	MF_ST_MARTIN("mf.svg"),
	MG_MADAGASCAR("mg.svg"),
	MH_MARSHALL_ISLANDS("mh.svg"),
	MK_MACEDONIA("mk.svg"),
	ML_MALI("ml.svg"),
	MM_MYANMAR("mm.svg"),
	MN_MONGOLIA("mn.svg"),
	MO_MACAU("mo.svg"),
	MP_NORTHERN_MARIANA_ISLANDS("mp.svg"),
	MQ_MARTINIQUE("mq.svg"),
	MR_MAURITANIA("mr.svg"),
	MS_MONTSERRAT("ms.svg"),
	MT_MALTA("mt.svg"),
	MU_MAURITIUS("mu.svg"),
	MV_MALDIVES("mv.svg"),
	MW_MALAWI("mw.svg"),
	MX_MEXICO("mx.svg"),
	MY_MALAYSIA("my.svg"),
	MZ_MOZAMBIQUE("mz.svg"),
	NA_NAMIBIA("na.svg"),
	NC_NEW_CALEDONIA("nc.svg"),
	NE_NIGER("ne.svg"),
	NF_NORFOLK_ISLAND("nf.svg"),
	NG_NIGERIA("ng.svg"),
	NI_NICARAGUA("ni.svg"),
	NL_NETHERLANDS("nl.svg"),
	NO_NORWAY("no.svg"),
	NP_NEPAL("np.svg"),
	NR_NAURU("nr.svg"),
	NU_NIUE("nu.svg"),
	NZ_NEW_ZEALAND("nz.svg"),
	OM_OMAN("om.svg"),
	PA_PANAMA("pa.svg"),
	PE_PERU("pe.svg"),
	PF_FRENCH_POLYNESIA("pf.svg"),
	PG_PAPUA_NEW_GUINEA("pg.svg"),
	PH_PHILIPPINES("ph.svg"),
	PK_PAKISTAN("pk.svg"),
	PL_POLAND("pl.svg"),
	PM_ST_PIERRE_MIQUELON("pm.svg"),
	PN_PITCAIRN_ISLANDS("pn.svg"),
	PR_PUERTO_RICO("pr.svg"),
	PS_PALESTINE("ps.svg"),
	PT_PORTUGAL("pt.svg"),
	PW_PALAU("pw.svg"),
	PY_PARAGUAY("py.svg"),
	QA_QATAR("qa.svg"),
	RE_REUNION("re.svg"),
	RO_ROMANIA("ro.svg"),
	RS_SERBIA("rs.svg"),
	RU_RUSSIA("ru.svg"),
	RW_RWANDA("rw.svg"),
	SA_SAUDI_ARABIA("sa.svg"),
	SB_SOLOMON_ISLANDS("sb.svg"),
	SC_SEYCHELLES("sc.svg"),
	SD_SUDAN("sd.svg"),
	SE_SWEDEN("se.svg"),
	SG_SINGAPORE("sg.svg"),
	SH_ST_HELENA("sh.svg"),
	SI_SLOVENIA("si.svg"),
	SJ_SVALBARD_JAN_MAYEN("sj.svg"),
	SK_SLOVAKIA("sk.svg"),
	SL_SIERRA_LEONE("sl.svg"),
	SM_SAN_MARINO("sm.svg"),
	SN_SENEGAL("sn.svg"),
	SO_SOMALIA("so.svg"),
	SR_SURINAME("sr.svg"),
	SS_SOUTH_SUDAN("ss.svg"),
	ST_SAO_TOME_PRINCIPE("st.svg"),
	SV_EL_SALVADOR("sv.svg"),
	SX_SINT_MAARTEN("sx.svg"),
	SY_SYRIA("sy.svg"),
	SZ_SWAZILAND("sz.svg"),
	TC_TURKS_CAICOS_ISLANDS("tc.svg"),
	TD_CHAD("td.svg"),
	TF_FRENCH_SOUTHERN_TERRITORIES("tf.svg"),
	TG_TOGO("tg.svg"),
	TH_THAILAND("th.svg"),
	TJ_TAJIKISTAN("tj.svg"),
	TK_TOKELAU("tk.svg"),
	TL_TIMOR_LESTE("tl.svg"),
	TM_TURKMENISTAN("tm.svg"),
	TN_TUNISIA("tn.svg"),
	TO_TONGA("to.svg"),
	TR_TURKEY("tr.svg"),
	TT_TRINIDAD_TOBAGO("tt.svg"),
	TV_TUVALU("tv.svg"),
	TW_TAIWAN("tw.svg"),
	TZ_TANZANIA("tz.svg"),
	UA_UKRAINE("ua.svg"),
	UG_UGANDA("ug.svg"),
	UM_US_OUTLYING_ISLANDS("um.svg"),
	UN_UNITED_NATIONS("un.svg"),
	US_UNITED_STATES("us.svg"),
	UY_URUGUAY("uy.svg"),
	UZ_UZBEKISTAN("uz.svg"),
	VA_VATICAN_CITY("va.svg"),
	VC_ST_VINCENT_GRENADINES("vc.svg"),
	VE_VENEZUELA("ve.svg"),
	VG_BRITISH_VIRGIN_ISLANDS("vg.svg"),
	VI_US_VIRGIN_ISLANDS("vi.svg"),
	VN_VIETNAM("vn.svg"),
	VU_VANUATU("vu.svg"),
	WF_WALLIS_FUTUNA("wf.svg"),
	WS_SAMOA("ws.svg"),
	XK_KOSOVO("xk.svg"),
	YE_YEMEN("ye.svg"),
	YT_MAYOTTE("yt.svg"),
	ZA_SOUTH_AFRICA("za.svg"),
	ZM_ZAMBIA("zm.svg"),
	ZW_ZIMBABWE("zw.svg"),

	;

	private String iconName;

	FlagIcon(String iconName) {
		this.iconName = iconName;
	}

	@Override
	public String getIconName() {
		return iconName;
	}

	@Override
	public String getIconLibraryId() {
		return FlagsIconProvider.LIBRARY_ID;
	}

}
